name: Build Dev App APK

on: 
  push:
    branches: 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'dev'
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_STOREPASSWORD: ${{ secrets.STORE_PASSWORD }}
      - run: flutter upgrade
      - run: flutter pub get
      - run: flutter build apk 
      - uses: actions/upload-artifact@v2
        with:
          name: dev-apk
          path: build/app/outputs/apk/release/app-release.apk    
